Add borrow_with to LazyCell
indiv0/lazycell pull request #56
Opened 2016-12-07 03:04 UTC by archer884

2016-12-07 08:08 UTC, archer884 commented
Also, sorry, I really meant to open this pr against my fork, because I actually have not gotten the chance to go over the contributing.md yet. :(

2016-12-07 09:37 UTC, indiv0 commented
No worries :)

Once you've read through the CONTRIBUTING.md and got the PR up to standard, just ping me and I'll review it.

2016-12-07 09:39 UTC, archer884 commented
@indiv0 Actually I think it's good now... Looked like I just needed to fix the commit message? Be happy to fix anything else that comes up.

2016-12-07 09:51 UTC, indiv0 commented on src/lib.rs
> +        let mut slot = unsafe {&mut *self.inner.get() };
Please add a space before `&mut` (i.e. `{ &mut`). Picky, I know.

2016-12-07 09:55 UTC, archer884 commented on src/lib.rs
> +        let mut slot = unsafe {&mut *self.inner.get() };
No, not picky at all--that's an embarrassing oversight on my part. :p

2016-12-07 09:56 UTC, indiv0 requested changes
Sorry for the very nitpicky review. Overall I agree it and I think it'll be a good addition to the API.

2016-12-07 09:56 UTC, indiv0 commented on src/lib.rs
> +    /// itself
Please add a period at the end of the sentence.

2016-12-07 09:56 UTC, indiv0 commented on src/lib.rs
> +    /// If the underlying value of the cell has not yet been realized, the
Could you replace this sentence with: "If the cell has not yet been filled, the cell is first filled using the function provided"

2016-12-07 09:56 UTC, indiv0 commented on src/lib.rs
> +        assert_eq!(&1, value);
Could you also test the positive case (i.e. `borrow_with(|| 1)` on a cell that's already been filled (just for complete test coverage).

2016-12-07 09:56 UTC, indiv0 commented on src/lib.rs
> +        slot.as_ref().unwrap()
Could you rewrite the function to be:

```rust
...
if !slot.is_some() {
    *slot = Some(f());
}

slot.as_ref().unwrap()
```

2016-12-07 09:56 UTC, archer884 commented
@indiv0 Do you have any idea why coveralls is complaining about this? I guess I may not understand how the coverage test is intended to work, but it seems weird that it would go down so much--seems like the new code would be covered? oO

2016-12-07 09:58 UTC, indiv0 commented
Coveralls is complaining so much (I believe) because `kcov` changed how they handle Rust code a while back, so it was artificially inflated before. I haven't modified the codebase since then, so that's why the drop occurs in your PR. I think if you add the "positive case" I mentioned above, it'll push the PR over the 80% minimum again.

Also, don't forget to add yourself to the `CONTRIBUTORS.md`!

2016-12-07 09:58 UTC, archer884 commented on src/lib.rs
> +        assert_eq!(&1, value);
Yes, I'll make a note to write that up. I was also thinking a test to assert that the `|| filler_func` only gets called once would be appropriate.

2016-12-07 18:36 UTC, archer884 commented
@indiv0 Looks like you were right about that coverage--and I think I now have a better understanding of what it's asking about. Don't worry about the review! Not nitpicky at all. :)

Was just thinking that I did not update the version in `Cargo.toml` and that's not in the contributing doc, either--is that something that clog is going to do? If so, that's kinda neat.

2016-12-08 04:33 UTC, indiv0 commented
*sigh* coveralls is still being weird. But that's fine. Updating the version and making a release must be done manually, unfortunately, but that's something I'll handle on my end, right now.

Thank you very much for this PR!

2016-12-08 04:33 UTC, merged

2016-12-08 04:56 UTC, indiv0 commented
Actually I think I figured out the source of the remaining weirdness. Coveralls is being run for both Linux and OS X builds, and they're giving differing results. I'll probably disable one to avoid this.

2016-12-08 04:59 UTC, indiv0 commented
Either way, v0.5.0 is published. Thanks again!

https://github.com/indiv0/lazycell/releases/tag/v0.5.0
https://crates.io/crates/lazycell/0.5.0