Add #![no_std]
indiv0/lazycell pull request #85
Opened 2018-06-05 16:51 UTC by est31

This crate uses nothing from the std crate that's not already
present in libcore. Therefore, add a #![no_std] mode.

2018-06-05 19:32 UTC, indiv0 requested changes
Moving to no_std sounds good to me. Would you mind adding yourself to the contributors file and to change the commit message format to follow the format described in CONTRIBUTING.md though?

2018-06-05 21:13 UTC, est31 commented
@indiv0 I've adjusted the PR. After merging, could you make a release to crates.io? That would be wonderful.

2018-06-06 00:02 UTC, indiv0 approved these changes

2018-06-06 00:02 UTC, merged

2018-06-06 00:20 UTC, indiv0 commented
Sure thing. I'll get right on it.